// This file was generated by scripts/generate-api-client.ts. Do not edit manually.

export type EmptyObject = Record<never, never>;
export type HeaderInit = ConstructorParameters<typeof Headers>[0];
export type HttpMethod = "DELETE" | "GET" | "PATCH" | "POST" | "PUT";

export interface ApiOperation<Params extends object, Query extends object, Body, ResponseBody> {
  params: Params;
  query: Query;
  body: Body;
  response: ResponseBody;
}

export interface ApiOperations {
  deleteApiActiveSessionsByTaskTaskId: ApiOperation<
    {
      taskId: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  deleteApiActiveSessionsId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  deleteApiBudgetsScopeScopeId: ApiOperation<
    {
      scope: "global" | "agent" | "user";
      scopeId: string;
    },
    EmptyObject,
    never,
    void
  >;
  deleteApiConfigId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  deleteApiKvKey: ApiOperation<
    {
      key: string;
    },
    EmptyObject,
    never,
    void
  >;
  deleteApiKvNamespaceKey: ApiOperation<
    {
      namespace: string;
      key: string;
    },
    EmptyObject,
    never,
    void
  >;
  deleteApiMcpOauthMcpServerId: ApiOperation<
    {
      mcpServerId: string;
    },
    {
      userId?: string;
    },
    never,
    unknown
  >;
  deleteApiMcpServersId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  deleteApiMcpServersIdInstallAgentId: ApiOperation<
    {
      id: string;
      agentId: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  deleteApiMemoryId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  deleteApiPagesId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    void
  >;
  deleteApiPricingProviderModelTokenClassEffectiveFrom: ApiOperation<
    {
      provider: "claude" | "claude-managed" | "codex" | "pi" | "opencode" | "devin" | "gemini";
      model: string;
      tokenClass: "input" | "cached_input" | "output" | "cache_write" | "runtime_hour" | "acu";
      effectiveFrom: string;
    },
    EmptyObject,
    never,
    void
  >;
  deleteApiPromptTemplatesId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  deleteApiReposId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    {
      success: boolean;
    }
  >;
  deleteApiSchedulesId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  deleteApiSkillsId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  deleteApiSkillsIdFilesPath: ApiOperation<
    {
      id: string;
      path: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  deleteApiSkillsIdInstallAgentId: ApiOperation<
    {
      id: string;
      agentId: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  deleteApiTrackersJiraDisconnect: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  deleteApiTrackersJiraWebhookId: ApiOperation<
    {
      id: number;
    },
    EmptyObject,
    never,
    unknown
  >;
  deleteApiTrackersLinearDisconnect: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  deleteApiUsersIdIdentitiesKindExternalId: ApiOperation<
    {
      id: string;
      kind: string;
      externalId: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  deleteApiUsersIdMcpTokensTokenId: ApiOperation<
    {
      id: string;
      tokenId: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  deleteApiWorkflowsId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    void
  >;
  deleteSwarmApiPath: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  getApiActiveSessions: ApiOperation<
    EmptyObject,
    {
      agentId?: string;
    },
    never,
    unknown
  >;
  getApiAgents: ApiOperation<
    EmptyObject,
    {
      include?: "tasks";
      fields?: "full" | "slim";
    },
    never,
    unknown
  >;
  getApiAgentsCredentialStatus: ApiOperation<
    EmptyObject,
    {
      status?: "idle" | "busy" | "offline" | "waiting_for_credentials";
    },
    never,
    unknown
  >;
  getApiAgentsId: ApiOperation<
    {
      id: string;
    },
    {
      include?: "tasks";
    },
    never,
    unknown
  >;
  getApiAgentsIdCredentialStatus: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  getApiAgentsIdMcpServers: ApiOperation<
    {
      id: string;
    },
    {
      resolveSecrets?: string;
    },
    never,
    unknown
  >;
  getApiAgentsIdSetupScript: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  getApiAgentsIdSkills: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  getApiAgentsIdSkillsSignature: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  getApiApprovalRequests: ApiOperation<
    EmptyObject,
    {
      status?: string;
      workflowRunId?: string;
      limit?: number | null;
    },
    never,
    unknown
  >;
  getApiApprovalRequestsId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  getApiBudgets: ApiOperation<
    EmptyObject,
    EmptyObject,
    never,
    {
      budgets: Array<{
        scope: "global" | "agent" | "user";
        scopeId: string;
        dailyBudgetUsd: number;
        createdAt: number;
        lastUpdatedAt: number;
      }>;
    }
  >;
  getApiBudgetsRefusals: ApiOperation<
    EmptyObject,
    {
      limit?: number;
    },
    never,
    {
      refusals: Array<{
        taskId: string;
        date: string;
        agentId: string;
        cause: "agent" | "global" | "user";
        agentSpendUsd?: number | null;
        agentBudgetUsd?: number | null;
        globalSpendUsd?: number | null;
        globalBudgetUsd?: number | null;
        userSpendUsd?: number | null;
        userBudgetUsd?: number | null;
        followUpTaskId?: string | null;
        createdAt: number;
      }>;
    }
  >;
  getApiBudgetsScopeScopeId: ApiOperation<
    {
      scope: "global" | "agent" | "user";
      scopeId: string;
    },
    EmptyObject,
    never,
    {
      scope: "global" | "agent" | "user";
      scopeId: string;
      dailyBudgetUsd: number;
      createdAt: number;
      lastUpdatedAt: number;
    }
  >;
  getApiConcurrentContext: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  getApiConfig: ApiOperation<
    EmptyObject,
    {
      scope?: string;
      scopeId?: string;
      includeSecrets?: "true" | "false";
    },
    never,
    unknown
  >;
  getApiConfigEnvPresence: ApiOperation<
    EmptyObject,
    {
      keys: string;
    },
    never,
    unknown
  >;
  getApiConfigId: ApiOperation<
    {
      id: string;
    },
    {
      includeSecrets?: "true" | "false";
    },
    never,
    unknown
  >;
  getApiConfigResolved: ApiOperation<
    EmptyObject,
    {
      agentId?: string;
      repoId?: string;
      includeSecrets?: "true" | "false";
    },
    never,
    unknown
  >;
  getApiEvents: ApiOperation<
    EmptyObject,
    {
      category?: "tool" | "skill" | "session" | "api" | "task" | "workflow" | "system";
      event?:
        | "tool.start"
        | "tool.end"
        | "skill.invoke"
        | "skill.complete"
        | "session.start"
        | "session.end"
        | "session.resume"
        | "session.cost"
        | "api.request"
        | "api.error"
        | "task.poll"
        | "task.assign"
        | "task.timeout"
        | "workflow.step.start"
        | "workflow.step.end"
        | "workflow.run.start"
        | "workflow.run.end"
        | "system.boot"
        | "system.migration"
        | "system.error"
        | "script.global_upsert";
      status?: "ok" | "error" | "timeout" | "skipped";
      source?: "worker" | "api" | "hook" | "scheduler" | "cli";
      agentId?: string;
      taskId?: string;
      sessionId?: string;
      since?: string;
      until?: string;
      limit?: number;
    },
    never,
    unknown
  >;
  getApiEventsCounts: ApiOperation<
    EmptyObject,
    {
      category?: "tool" | "skill" | "session" | "api" | "task" | "workflow" | "system";
      source?: "worker" | "api" | "hook" | "scheduler" | "cli";
      agentId?: string;
      taskId?: string;
      sessionId?: string;
      since?: string;
      until?: string;
    },
    never,
    unknown
  >;
  getApiExecutorTypes: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  getApiExecutorTypesType: ApiOperation<
    {
      type: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  getApiInboxState: ApiOperation<
    EmptyObject,
    {
      userId: string;
      status?: "open" | "snoozed" | "dismissed" | "done";
      itemType?:
        | "approval"
        | "credential_missing"
        | "broken_task"
        | "to_read"
        | "to_start_template";
    },
    never,
    unknown
  >;
  getApiIntegrationsMcpUserConfig: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  getApiKeysAvailable: ApiOperation<
    EmptyObject,
    {
      keyType: string;
      totalKeys: number;
      scope?: string;
      scopeId?: string;
    },
    never,
    unknown
  >;
  getApiKeysCosts: ApiOperation<
    EmptyObject,
    {
      keyType?: string;
    },
    never,
    unknown
  >;
  getApiKeysStatus: ApiOperation<
    EmptyObject,
    {
      keyType?: string;
      scope?: string;
      scopeId?: string;
    },
    never,
    unknown
  >;
  getApiKv: ApiOperation<
    EmptyObject,
    {
      prefix?: string;
      limit?: number;
      offset?: number | null;
    },
    never,
    unknown
  >;
  getApiKvKey: ApiOperation<
    {
      key: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  getApiKvNamespace: ApiOperation<
    {
      namespace: string;
    },
    {
      prefix?: string;
      limit?: number;
      offset?: number | null;
    },
    never,
    unknown
  >;
  getApiKvNamespaceKey: ApiOperation<
    {
      namespace: string;
      key: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  getApiLogs: ApiOperation<
    EmptyObject,
    {
      limit?: number;
      agentId?: string;
    },
    never,
    unknown
  >;
  getApiMcpOauthCallback: ApiOperation<
    EmptyObject,
    {
      code?: string;
      state?: string;
      error?: string;
      error_description?: string;
    },
    never,
    unknown
  >;
  getApiMcpOauthMcpServerIdAuthorize: ApiOperation<
    {
      mcpServerId: string;
    },
    {
      redirect?: string;
      userId?: string;
      scopes?: string;
    },
    never,
    unknown
  >;
  getApiMcpOauthMcpServerIdAuthorizeUrl: ApiOperation<
    {
      mcpServerId: string;
    },
    {
      redirect?: string;
      userId?: string;
      scopes?: string;
    },
    never,
    unknown
  >;
  getApiMcpOauthMcpServerIdMetadata: ApiOperation<
    {
      mcpServerId: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  getApiMcpOauthMcpServerIdStatus: ApiOperation<
    {
      mcpServerId: string;
    },
    {
      userId?: string;
    },
    never,
    unknown
  >;
  getApiMcpServers: ApiOperation<
    EmptyObject,
    {
      scope?: string;
      transport?: string;
      ownerAgentId?: string;
      enabled?: string;
      search?: string;
    },
    never,
    unknown
  >;
  getApiMcpServersId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  getApiMemoryEdges: ApiOperation<
    EmptyObject,
    {
      memoryId: string;
    },
    never,
    unknown
  >;
  getApiMemoryHealth: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  getApiMemoryId: ApiOperation<
    {
      id: string;
    },
    {
      intent?: string;
    },
    never,
    unknown
  >;
  getApiMemoryRetrievals: ApiOperation<
    EmptyObject,
    {
      taskId?: string;
      sessionId?: string;
    },
    never,
    unknown
  >;
  getApiMetrics: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  getApiPages: ApiOperation<
    EmptyObject,
    {
      agentId?: string;
      limit?: number;
      offset?: number | null;
      fields?: "full" | "slim";
    },
    never,
    unknown
  >;
  getApiPagesActions: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  getApiPagesId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  getApiPagesIdVersions: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  getApiPagesIdVersionsVersion: ApiOperation<
    {
      id: string;
      version: number;
    },
    EmptyObject,
    never,
    unknown
  >;
  getApiPausedTasks: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  getApiPoll: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  getApiPricing: ApiOperation<
    EmptyObject,
    EmptyObject,
    never,
    {
      rows: Array<{
        provider: "claude" | "claude-managed" | "codex" | "pi" | "opencode" | "devin" | "gemini";
        model: string;
        tokenClass: "input" | "cached_input" | "output" | "cache_write" | "runtime_hour" | "acu";
        effectiveFrom: number;
        pricePerMillionUsd: number;
        createdAt: number;
        lastUpdatedAt: number;
      }>;
    }
  >;
  getApiPricingProviderModelTokenClass: ApiOperation<
    {
      provider: "claude" | "claude-managed" | "codex" | "pi" | "opencode" | "devin" | "gemini";
      model: string;
      tokenClass: "input" | "cached_input" | "output" | "cache_write" | "runtime_hour" | "acu";
    },
    EmptyObject,
    never,
    unknown
  >;
  getApiPricingProviderModelTokenClassActive: ApiOperation<
    {
      provider: "claude" | "claude-managed" | "codex" | "pi" | "opencode" | "devin" | "gemini";
      model: string;
      tokenClass: "input" | "cached_input" | "output" | "cache_write" | "runtime_hour" | "acu";
    },
    EmptyObject,
    never,
    {
      provider: "claude" | "claude-managed" | "codex" | "pi" | "opencode" | "devin" | "gemini";
      model: string;
      tokenClass: "input" | "cached_input" | "output" | "cache_write" | "runtime_hour" | "acu";
      effectiveFrom: number;
      pricePerMillionUsd: number;
      createdAt: number;
      lastUpdatedAt: number;
    }
  >;
  getApiPromptTemplates: ApiOperation<
    EmptyObject,
    {
      eventType?: string;
      scope?: string;
      scopeId?: string;
      isDefault?: "true" | "false";
    },
    never,
    unknown
  >;
  getApiPromptTemplatesEvents: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  getApiPromptTemplatesId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  getApiPromptTemplatesResolved: ApiOperation<
    EmptyObject,
    {
      eventType: string;
      agentId?: string;
      repoId?: string;
    },
    never,
    unknown
  >;
  getApiRepos: ApiOperation<
    EmptyObject,
    {
      autoClone?: "true" | "false";
      name?: string;
    },
    never,
    {
      repos: Array<{
        id: string;
        url: string;
        name: string;
        clonePath: string;
        defaultBranch?: string;
        autoClone?: boolean;
        hooks?: {
          enabled?: boolean;
        };
        guidelines?:
          | {
              prChecks: Array<string>;
              mergeChecks: Array<string>;
              allowMerge?: boolean;
              review: Array<string>;
            }
          | {
              prChecks: Array<string>;
              mergeChecks: Array<string>;
              allowMerge?: boolean;
              review: Array<string>;
            };
        createdAt: string;
        lastUpdatedAt: string;
      }>;
    }
  >;
  getApiReposId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    {
      id: string;
      url: string;
      name: string;
      clonePath: string;
      defaultBranch?: string;
      autoClone?: boolean;
      hooks?: {
        enabled?: boolean;
      };
      guidelines?:
        | {
            prChecks: Array<string>;
            mergeChecks: Array<string>;
            allowMerge?: boolean;
            review: Array<string>;
          }
        | {
            prChecks: Array<string>;
            mergeChecks: Array<string>;
            allowMerge?: boolean;
            review: Array<string>;
          };
      createdAt: string;
      lastUpdatedAt: string;
    }
  >;
  getApiScheduledTasks: ApiOperation<
    EmptyObject,
    {
      enabled?: "true" | "false";
      name?: string;
      scheduleType?: "recurring" | "one_time";
      hideCompleted?: "true" | "false";
    },
    never,
    unknown
  >;
  getApiSchedules: ApiOperation<
    EmptyObject,
    {
      enabled?: "true" | "false";
      name?: string;
      scheduleType?: "recurring" | "one_time";
      hideCompleted?: "true" | "false";
      fields?: "full" | "slim";
    },
    never,
    unknown
  >;
  getApiSchedulesId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  getApiServices: ApiOperation<
    EmptyObject,
    {
      status?: string;
      agentId?: string;
      name?: string;
    },
    never,
    unknown
  >;
  getApiSessionCosts: ApiOperation<
    EmptyObject,
    {
      agentId?: string;
      taskId?: string;
      startDate?: string;
      endDate?: string;
      limit?: number;
    },
    never,
    unknown
  >;
  getApiSessionCostsDashboard: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  getApiSessionCostsSummary: ApiOperation<
    EmptyObject,
    {
      groupBy?: "day" | "agent" | "both";
      startDate?: string;
      endDate?: string;
      agentId?: string;
    },
    never,
    unknown
  >;
  getApiSessions: ApiOperation<
    EmptyObject,
    {
      limit?: number | null;
      offset?: number | null;
      source?: string;
      q?: string;
      requestedByUserId?: string;
      fields?: "full" | "slim";
    },
    never,
    unknown
  >;
  getApiSessionsRootTaskId: ApiOperation<
    {
      rootTaskId: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  getApiSkills: ApiOperation<
    EmptyObject,
    {
      type?: string;
      scope?: string;
      agentId?: string;
      enabled?: string;
      search?: string;
      fields?: "full" | "slim";
    },
    never,
    unknown
  >;
  getApiSkillsId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  getApiSkillsIdFiles: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  getApiSkillsIdFilesPath: ApiOperation<
    {
      id: string;
      path: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  getApiStats: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  getApiTasks: ApiOperation<
    EmptyObject,
    {
      status?: string;
      agentId?: string;
      scheduleId?: string;
      search?: string;
      includeHeartbeat?: "true" | "false";
      createdAfter?: string;
      source?: string;
      limit?: number | null;
      offset?: number | null;
      fields?: "full" | "slim";
    },
    never,
    unknown
  >;
  getApiTasksId: ApiOperation<
    {
      id: string;
    },
    {
      logsLimit?: number;
    },
    never,
    unknown
  >;
  getApiTasksIdContext: ApiOperation<
    {
      id: string;
    },
    {
      limit?: number;
    },
    never,
    unknown
  >;
  getApiTasksTaskIdSessionLogs: ApiOperation<
    {
      taskId: string;
    },
    {
      limit?: number;
    },
    never,
    unknown
  >;
  getApiTaskTemplates: ApiOperation<
    EmptyObject,
    {
      category?: string;
      kind?: "task" | "workflow" | "schedule";
      query?: string;
    },
    never,
    unknown
  >;
  getApiTrackersJiraAuthorize: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  getApiTrackersJiraCallback: ApiOperation<
    EmptyObject,
    {
      code: string;
      state: string;
    },
    never,
    unknown
  >;
  getApiTrackersJiraStatus: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  getApiTrackersLinearAuthorize: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  getApiTrackersLinearCallback: ApiOperation<
    EmptyObject,
    {
      code: string;
      state: string;
    },
    never,
    unknown
  >;
  getApiTrackersLinearStatus: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  getApiUsers: ApiOperation<
    EmptyObject,
    {
      recentEvents?: number | null;
    },
    never,
    unknown
  >;
  getApiUsersId: ApiOperation<
    {
      id: string;
    },
    {
      recentEvents?: number | null;
    },
    never,
    unknown
  >;
  getApiUsersIdEvents: ApiOperation<
    {
      id: string;
    },
    {
      limit?: number;
      before?: string;
    },
    never,
    unknown
  >;
  getApiUsersUnmapped: ApiOperation<
    EmptyObject,
    {
      kind?: string;
      limit?: number;
    },
    never,
    unknown
  >;
  getApiWorkflowRunsId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  getApiWorkflows: ApiOperation<
    EmptyObject,
    {
      fields?: "full" | "slim";
    },
    never,
    unknown
  >;
  getApiWorkflowsId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  getApiWorkflowsIdRuns: ApiOperation<
    {
      id: string;
    },
    {
      status?: "running" | "waiting" | "completed" | "failed" | "skipped" | "cancelled";
    },
    never,
    unknown
  >;
  getApiWorkflowsIdVersions: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  getApiWorkflowsIdVersionsVersion: ApiOperation<
    {
      id: string;
      version: number;
    },
    EmptyObject,
    never,
    unknown
  >;
  getEcosystem: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  getPId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  getPIdJson: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  getStatus: ApiOperation<
    EmptyObject,
    EmptyObject,
    never,
    {
      identity: {
        name: string;
        logo_url: string | null;
        brand_color: string | null;
        is_cloud: boolean;
        marketing_url: string | null;
        hide_cloud_promo: boolean;
        org_id: string | null;
      };
      setup: Array<{
        id: "harness" | "slack" | "github" | "linear" | "jira" | "workers" | "first_task";
        label: string;
        state: "unverified" | "configured" | "verified";
        hint?: string;
        action_url?: string;
        provider?: "claude" | "codex" | "pi" | "devin" | "claude-managed" | "opencode";
        providers?: Array<{
          provider: "claude" | "codex" | "pi" | "devin" | "claude-managed" | "opencode";
          state: "unverified" | "configured" | "verified";
          workers: number;
        }>;
      }>;
      activity: {
        agents_online: number;
        leads_online: number;
        recent_tasks_count: number;
      };
      agent_fs: {
        configured: boolean;
        base_url: string | null;
      };
      health: "ok" | "degraded" | "broken";
    }
  >;
  getSwarmApiPath: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  patchApiAgentsIdHarnessProvider: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      harness_provider: "claude" | "codex" | "pi" | "devin" | "claude-managed" | "opencode";
    },
    unknown
  >;
  patchApiAgentsIdRuntime: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      harness_provider: "claude" | "codex" | "pi" | "opencode";
      model: string;
      allow_custom_model?: boolean;
    },
    unknown
  >;
  patchApiInboxState: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      userId: string;
      itemType: "approval" | "credential_missing" | "broken_task" | "to_read" | "to_start_template";
      itemId: string;
      status: "open" | "snoozed" | "dismissed" | "done";
      snoozeUntil?: string;
    },
    unknown
  >;
  patchApiKeysName: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      keyType: string;
      keySuffix: string;
      name: string | null;
      scope?: string;
      scopeId?: string;
    },
    unknown
  >;
  patchApiTasksIdVcs: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      vcsProvider: "github" | "gitlab";
      vcsRepo: string;
      vcsNumber: number;
      vcsUrl: string;
    },
    unknown
  >;
  patchApiUsersId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      name?: string;
      email?: string;
      role?: string;
      notes?: string;
      emailAliases?: Array<string>;
      preferredChannel?: string;
      timezone?: string;
      metadata?: {
        [key: string]: unknown;
      } | null;
      dailyBudgetUsd?: number | null;
      status?: "invited" | "active" | "suspended";
      identities?: Array<{
        kind: string;
        externalId: string;
      }>;
    },
    unknown
  >;
  patchApiWorkflowsId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      update?: Array<{
        nodeId: string;
        node: {
          type?: string;
          label?: string;
          config?: {
            [key: string]: unknown;
          };
          next?:
            | string
            | Array<string>
            | {
                [key: string]: string;
              };
          validation?: {
            executor?: string;
            config: {
              [key: string]: unknown;
            };
            mustPass?: boolean;
            retry?: {
              maxRetries?: number;
              strategy?: "exponential" | "static" | "linear";
              baseDelayMs?: number;
              maxDelayMs?: number;
            };
          };
          retry?: {
            maxRetries?: number;
            strategy?: "exponential" | "static" | "linear";
            baseDelayMs?: number;
            maxDelayMs?: number;
          };
          inputs?: {
            [key: string]: string;
          };
          inputSchema?: {
            [key: string]: unknown;
          };
          outputSchema?: {
            [key: string]: unknown;
          };
        };
      }>;
      delete?: Array<string>;
      create?: Array<{
        id: string;
        type: string;
        label?: string;
        config: {
          [key: string]: unknown;
        };
        next?:
          | string
          | Array<string>
          | {
              [key: string]: string;
            };
        validation?: {
          executor?: string;
          config: {
            [key: string]: unknown;
          };
          mustPass?: boolean;
          retry?: {
            maxRetries?: number;
            strategy?: "exponential" | "static" | "linear";
            baseDelayMs?: number;
            maxDelayMs?: number;
          };
        };
        retry?: {
          maxRetries?: number;
          strategy?: "exponential" | "static" | "linear";
          baseDelayMs?: number;
          maxDelayMs?: number;
        };
        inputs?: {
          [key: string]: string;
        };
        inputSchema?: {
          [key: string]: unknown;
        };
        outputSchema?: {
          [key: string]: unknown;
        };
      }>;
      onNodeFailure?: "fail" | "continue";
      triggerSchema?: {
        [key: string]: unknown;
      } | null;
    },
    unknown
  >;
  patchApiWorkflowsIdNodesNodeId: ApiOperation<
    {
      id: string;
      nodeId: string;
    },
    EmptyObject,
    {
      type?: string;
      label?: string;
      config?: {
        [key: string]: unknown;
      };
      next?:
        | string
        | Array<string>
        | {
            [key: string]: string;
          };
      validation?: {
        executor?: string;
        config: {
          [key: string]: unknown;
        };
        mustPass?: boolean;
        retry?: {
          maxRetries?: number;
          strategy?: "exponential" | "static" | "linear";
          baseDelayMs?: number;
          maxDelayMs?: number;
        };
      };
      retry?: {
        maxRetries?: number;
        strategy?: "exponential" | "static" | "linear";
        baseDelayMs?: number;
        maxDelayMs?: number;
      };
      inputs?: {
        [key: string]: string;
      };
      inputSchema?: {
        [key: string]: unknown;
      };
      outputSchema?: {
        [key: string]: unknown;
      };
    },
    unknown
  >;
  patchSwarmApiPath: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  postApiActiveSessions: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      agentId: string;
      taskId?: string;
      triggerType: string;
      inboxMessageId?: string;
      taskDescription?: string;
      runnerSessionId?: string;
    },
    unknown
  >;
  postApiActiveSessionsCleanup: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      agentId?: string;
      maxAgeMinutes?: number;
    },
    unknown
  >;
  postApiActiveSessionsRecoverOrphanedTasks: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      agentId: string;
      minAgeSeconds?: number;
    },
    unknown
  >;
  postApiAgentmailWebhook: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  postApiAgents: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      name: string;
      isLead?: boolean;
      description?: string;
      role?: string;
      capabilities?: Array<string>;
      maxTasks?: number;
      provider?: "claude" | "codex" | "pi" | "devin" | "claude-managed" | "opencode";
      harness_provider?: "claude" | "codex" | "pi" | "devin" | "claude-managed" | "opencode";
    },
    unknown
  >;
  postApiApprovalRequests: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      title: string;
      questions: Array<{
        id: string;
        type: "approval" | "text" | "single-select" | "multi-select" | "boolean";
        label: string;
        required?: boolean;
        description?: string;
        placeholder?: string;
        multiline?: boolean;
        options?: Array<{
          value: string;
          label: string;
          description?: string;
        }>;
        minSelections?: number;
        maxSelections?: number;
        defaultValue?: boolean;
      }>;
      approvers: {
        users?: Array<string>;
        roles?: Array<string>;
        policy:
          | "any"
          | "all"
          | {
              min: number;
            };
      };
      workflowRunId?: string;
      workflowRunStepId?: string;
      sourceTaskId?: string;
      timeoutSeconds?: number;
      notifications?: Array<{
        channel: "slack" | "email";
        target: string;
      }>;
    },
    unknown
  >;
  postApiApprovalRequestsIdRespond: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      responses: {
        [key: string]: unknown;
      };
      respondedBy?: string;
    },
    unknown
  >;
  postApiChannelActivityCommitCursors: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      cursorUpdates: Array<{
        channelId: string;
        ts: string;
      }>;
    },
    unknown
  >;
  postApiConfigReload: ApiOperation<EmptyObject, EmptyObject, Record<string, unknown>, unknown>;
  postApiDbQuery: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      sql?: string;
      query?: string;
      params?: Array<unknown>;
    },
    {
      columns: Array<string>;
      rows: Array<Array<unknown>>;
      elapsed: number;
      total: number;
    }
  >;
  postApiEvents: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      category: "tool" | "skill" | "session" | "api" | "task" | "workflow" | "system";
      event:
        | "tool.start"
        | "tool.end"
        | "skill.invoke"
        | "skill.complete"
        | "session.start"
        | "session.end"
        | "session.resume"
        | "session.cost"
        | "api.request"
        | "api.error"
        | "task.poll"
        | "task.assign"
        | "task.timeout"
        | "workflow.step.start"
        | "workflow.step.end"
        | "workflow.run.start"
        | "workflow.run.end"
        | "system.boot"
        | "system.migration"
        | "system.error"
        | "script.global_upsert";
      status?: "ok" | "error" | "timeout" | "skipped";
      source: "worker" | "api" | "hook" | "scheduler" | "cli";
      agentId?: string;
      taskId?: string;
      sessionId?: string;
      parentEventId?: string;
      numericValue?: number;
      durationMs?: number;
      data?: {
        [key: string]: unknown;
      };
    },
    unknown
  >;
  postApiEventsBatch: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      events: Array<{
        category: "tool" | "skill" | "session" | "api" | "task" | "workflow" | "system";
        event:
          | "tool.start"
          | "tool.end"
          | "skill.invoke"
          | "skill.complete"
          | "session.start"
          | "session.end"
          | "session.resume"
          | "session.cost"
          | "api.request"
          | "api.error"
          | "task.poll"
          | "task.assign"
          | "task.timeout"
          | "workflow.step.start"
          | "workflow.step.end"
          | "workflow.run.start"
          | "workflow.run.end"
          | "system.boot"
          | "system.migration"
          | "system.error"
          | "script.global_upsert";
        status?: "ok" | "error" | "timeout" | "skipped";
        source: "worker" | "api" | "hook" | "scheduler" | "cli";
        agentId?: string;
        taskId?: string;
        sessionId?: string;
        parentEventId?: string;
        numericValue?: number;
        durationMs?: number;
        data?: {
          [key: string]: unknown;
        };
      }>;
    },
    unknown
  >;
  postApiGithubWebhook: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  postApiGitlabWebhook: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  postApiHeartbeatChecklist: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  postApiHeartbeatSweep: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  postApiIntegrationsClaudeManagedTest: ApiOperation<
    EmptyObject,
    EmptyObject,
    Record<string, unknown>,
    unknown
  >;
  postApiIntegrationsKapsoWebhook: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  postApiKeysClearRateLimit: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      keyType: string;
      keySuffix: string;
      scope?: string;
      scopeId?: string;
    },
    unknown
  >;
  postApiKeysReportRateLimit: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      keyType: string;
      keySuffix: string;
      keyIndex: number;
      rateLimitedUntil: string;
      scope?: string;
      scopeId?: string;
    },
    unknown
  >;
  postApiKeysReportRateLimitWindows: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      keyType: string;
      keySuffix: string;
      keyIndex: number;
      windows: {
        [key: string]: {
          status: string;
          utilization?: number;
          resetsAt?: number;
          isUsingOverage?: boolean;
          surpassedThreshold?: number;
          lastSeenAt: string;
        };
      };
      scope?: string;
      scopeId?: string;
    },
    unknown
  >;
  postApiKeysReportUsage: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      keyType: string;
      keySuffix: string;
      keyIndex: number;
      taskId?: string;
      scope?: string;
      scopeId?: string;
    },
    unknown
  >;
  postApiKvKeyIncr: ApiOperation<
    {
      key: string;
    },
    EmptyObject,
    | {
        by?: number;
      }
    | {
        by?: number;
      },
    unknown
  >;
  postApiKvNamespaceKeyIncr: ApiOperation<
    {
      namespace: string;
      key: string;
    },
    EmptyObject,
    | {
        by?: number;
      }
    | {
        by?: number;
      },
    unknown
  >;
  postApiMcpBridge: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      tool: string;
      args?: {
        [key: string]: unknown;
      };
    },
    unknown
  >;
  postApiMcpOauthMcpServerIdManualClient: ApiOperation<
    {
      mcpServerId: string;
    },
    EmptyObject,
    {
      clientId: string;
      clientSecret?: string;
      authorizationServerIssuer?: string;
      authorizeUrl?: string;
      tokenUrl?: string;
      revocationUrl?: string;
      scopes?: Array<string>;
    },
    unknown
  >;
  postApiMcpOauthMcpServerIdRefresh: ApiOperation<
    {
      mcpServerId: string;
    },
    EmptyObject,
    {
      userId?: string;
    },
    unknown
  >;
  postApiMcpServers: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      name: string;
      transport: "stdio" | "http" | "sse";
      description?: string;
      scope?: string;
      ownerAgentId?: string;
      command?: string;
      args?: string;
      url?: string;
      headers?: string;
      envConfigKeys?: string;
      headerConfigKeys?: string;
    },
    unknown
  >;
  postApiMcpServersIdInstall: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      agentId: string;
    },
    unknown
  >;
  postApiMemoryEdit: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      memoryId?: string;
      key?: string;
      scope?: "agent" | "swarm";
      mode?: "replace" | "exact";
      content?: string;
      oldString?: string;
      newString?: string;
      intent: string;
      expectedVersion?: number;
    },
    unknown
  >;
  postApiMemoryIndex: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      agentId?: string;
      content: string;
      name: string;
      scope: "agent" | "swarm";
      source: "manual" | "file_index" | "session_summary" | "task_completion";
      sourceTaskId?: string;
      sourcePath?: string;
      tags?: Array<string>;
      persistMemory?: boolean;
      contextKey?: string;
    },
    unknown
  >;
  postApiMemoryList: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      query?: string;
      agentId?: string;
      scope?: "agent" | "swarm" | "all";
      source?: "manual" | "file_index" | "session_summary" | "task_completion";
      sourcePath?: string;
      limit?: number;
      offset?: number;
    },
    unknown
  >;
  postApiMemoryRate: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      events: Array<{
        memoryId: string;
        signal: number;
        weight: number;
        source: "llm" | "explicit-self";
        reasoning?: string;
        taskId?: string;
        referencesSource?: string;
      }>;
    },
    unknown
  >;
  postApiMemoryReEmbed: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      agentId?: string;
      batchSize?: number;
    },
    unknown
  >;
  postApiMemorySearch: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      query: string;
      intent?: string;
      limit?: number;
      scope?: "agent" | "swarm" | "all";
      source?: "manual" | "file_index" | "session_summary" | "task_completion";
    },
    unknown
  >;
  postApiPages: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      slug?: string;
      title: string;
      description?: string;
      contentType: "text/html" | "application/json";
      authMode?: "public" | "authed" | "password";
      password?: string;
      body: string;
      needsCredentials?: Array<string>;
    },
    unknown
  >;
  postApiPagesIdLaunch: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    void
  >;
  postApiPricingProviderModelTokenClass: ApiOperation<
    {
      provider: "claude" | "claude-managed" | "codex" | "pi" | "opencode" | "devin" | "gemini";
      model: string;
      tokenClass: "input" | "cached_input" | "output" | "cache_write" | "runtime_hour" | "acu";
    },
    EmptyObject,
    {
      pricePerMillionUsd: number;
      effectiveFrom?: number;
    },
    {
      provider: "claude" | "claude-managed" | "codex" | "pi" | "opencode" | "devin" | "gemini";
      model: string;
      tokenClass: "input" | "cached_input" | "output" | "cache_write" | "runtime_hour" | "acu";
      effectiveFrom: number;
      pricePerMillionUsd: number;
      createdAt: number;
      lastUpdatedAt: number;
    }
  >;
  postApiPromptTemplatesIdCheckout: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      version: number;
    },
    unknown
  >;
  postApiPromptTemplatesIdReset: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  postApiPromptTemplatesPreview: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      eventType: string;
      body?: string;
      variables?: {
        [key: string]: unknown;
      };
    },
    unknown
  >;
  postApiPromptTemplatesRender: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      eventType: string;
      variables?: {
        [key: string]: unknown;
      };
      agentId?: string;
      repoId?: string;
    },
    unknown
  >;
  postApiRepos: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      url: string;
      name: string;
      clonePath?: string;
      defaultBranch?: string;
      autoClone?: boolean;
      hooks?: {
        enabled?: boolean;
      };
      guidelines?:
        | {
            prChecks: Array<string>;
            mergeChecks: Array<string>;
            allowMerge?: boolean;
            review: Array<string>;
          }
        | {
            prChecks: Array<string>;
            mergeChecks: Array<string>;
            allowMerge?: boolean;
            review: Array<string>;
          };
    },
    {
      id: string;
      url: string;
      name: string;
      clonePath: string;
      defaultBranch?: string;
      autoClone?: boolean;
      hooks?: {
        enabled?: boolean;
      };
      guidelines?:
        | {
            prChecks: Array<string>;
            mergeChecks: Array<string>;
            allowMerge?: boolean;
            review: Array<string>;
          }
        | {
            prChecks: Array<string>;
            mergeChecks: Array<string>;
            allowMerge?: boolean;
            review: Array<string>;
          };
      createdAt: string;
      lastUpdatedAt: string;
    }
  >;
  postApiSchedules: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      name: string;
      description?: string;
      cronExpression?: string;
      intervalMs?: number;
      taskTemplate: string;
      taskType?: string;
      tags?: Array<string>;
      priority?: number;
      targetAgentId?: string;
      enabled?: boolean;
      timezone?: string;
      model?: string;
      modelTier?: "smol" | "regular" | "smart" | "ultra";
      scheduleType?: "recurring" | "one_time";
      delayMs?: number;
      runAt?: string;
    },
    unknown
  >;
  postApiSchedulesIdRun: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  postApiSessionCosts: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      sessionId: string;
      agentId: string;
      totalCostUsd: number;
      taskId?: string;
      inputTokens?: number;
      outputTokens?: number;
      cacheReadTokens?: number;
      cacheWriteTokens?: number | null;
      reasoningOutputTokens?: number;
      thinkingTokens?: number;
      durationMs?: number;
      numTurns?: number | null;
      model?: string;
      isError?: boolean;
      provider?: "claude" | "claude-managed" | "codex" | "pi" | "opencode" | "devin" | "gemini";
      createdAt?: number;
    },
    unknown
  >;
  postApiSessionLogs: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      sessionId: string;
      iteration: number;
      lines: Array<string>;
      taskId?: string;
      cli?: string;
    },
    unknown
  >;
  postApiSkills: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      content: string;
      type?: string;
      scope?: string;
      ownerAgentId?: string;
      systemDefault?: boolean;
    },
    unknown
  >;
  postApiSkillsIdFiles: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      files: Array<{
        content: string;
        mimeType?: string;
        isBinary?: boolean;
        size?: number;
        path: string;
      }>;
    },
    unknown
  >;
  postApiSkillsIdInstall: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      agentId: string;
    },
    unknown
  >;
  postApiSkillsInstallRemote: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      sourceRepo: string;
      sourcePath?: string;
      scope?: string;
      isComplex?: boolean;
    },
    unknown
  >;
  postApiSkillsSyncFilesystem: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  postApiSkillsSyncRemote: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      skillId?: string;
      force?: boolean;
    },
    unknown
  >;
  postApiTasks: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      task: string;
      agentId?: string;
      taskType?: string;
      tags?: Array<string>;
      priority?: number;
      dependsOn?: Array<string>;
      offeredTo?: string;
      dir?: string;
      parentTaskId?: string;
      source?:
        | "mcp"
        | "slack"
        | "api"
        | "ui"
        | "github"
        | "gitlab"
        | "agentmail"
        | "system"
        | "schedule"
        | "workflow"
        | "linear"
        | "jira";
      outputSchema?: {
        [key: string]: unknown;
      };
      contextKey?: string;
      requestedByUserId?: string;
      model?: string;
      modelTier?: "smol" | "regular" | "smart" | "ultra";
    },
    unknown
  >;
  postApiTasksIdCancel: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  postApiTasksIdContext: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      eventType: "progress" | "compaction" | "completion";
      sessionId: string;
      contextUsedTokens?: number;
      contextTotalTokens?: number;
      contextPercent?: number;
      compactTrigger?: "auto" | "manual" | "auto-inferred";
      preCompactTokens?: number;
      cumulativeInputTokens?: number;
      cumulativeOutputTokens?: number;
      contextFormula?:
        | "input-cache-output"
        | "input-cache-no-output"
        | "input-output-no-cache"
        | "peak-proxy"
        | "pi-delegated"
        | "harness-reported"
        | "unknown";
    },
    unknown
  >;
  postApiTasksIdFinish: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      status: "completed" | "failed";
      output?: string;
      failureReason?: string;
    },
    unknown
  >;
  postApiTasksIdPause: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  postApiTasksIdProgress: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      progress: string;
    },
    unknown
  >;
  postApiTasksIdResume: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  postApiTasksIdSupersede: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      reason: "graceful_shutdown" | "context_limits" | "manual_supersede" | "crash_recovery";
    },
    unknown
  >;
  postApiTrackersJiraRefresh: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  postApiTrackersJiraWebhookRegister: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      jqlFilter: string;
    },
    unknown
  >;
  postApiTrackersJiraWebhookToken: ApiOperation<
    {
      token: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  postApiTrackersLinearRefresh: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  postApiTrackersLinearWebhook: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  postApiUsers: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      name: string;
      email?: string;
      role?: string;
      notes?: string;
      emailAliases?: Array<string>;
      preferredChannel?: string;
      timezone?: string;
      metadata?: {
        [key: string]: unknown;
      };
      dailyBudgetUsd?: number | null;
      status?: "invited" | "active" | "suspended";
      identities?: Array<{
        kind: string;
        externalId: string;
      }>;
    },
    unknown
  >;
  postApiUsersIdIdentities: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      kind: string;
      externalId: string;
    },
    unknown
  >;
  postApiUsersIdMcpTokens: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      label?: string | null;
    },
    unknown
  >;
  postApiUsersIdMerge: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      sourceUserId: string;
    },
    unknown
  >;
  postApiUsersUnmappedKindExternalIdResolve: ApiOperation<
    {
      kind: string;
      externalId: string;
    },
    EmptyObject,
    | {
        userId: string;
      }
    | {
        name: string;
        email?: string;
        notes?: string;
      },
    unknown
  >;
  postApiWebhooksWorkflowId: ApiOperation<
    {
      workflowId: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  postApiWorkflowEvents: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      name: string;
      payload?: {
        [key: string]: unknown;
      };
    },
    unknown
  >;
  postApiWorkflowRunsIdCancel: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      reason?: string;
    },
    unknown
  >;
  postApiWorkflowRunsIdRetry: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  postApiWorkflowRunsRunIdEvents: ApiOperation<
    {
      runId: string;
    },
    EmptyObject,
    {
      name: string;
      payload?: {
        [key: string]: unknown;
      };
    },
    unknown
  >;
  postApiWorkflows: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      name: string;
      description?: string;
      definition: {
        nodes: Array<{
          id: string;
          type: string;
          label?: string;
          config: {
            [key: string]: unknown;
          };
          next?:
            | string
            | Array<string>
            | {
                [key: string]: string;
              };
          validation?: {
            executor?: string;
            config: {
              [key: string]: unknown;
            };
            mustPass?: boolean;
            retry?: {
              maxRetries?: number;
              strategy?: "exponential" | "static" | "linear";
              baseDelayMs?: number;
              maxDelayMs?: number;
            };
          };
          retry?: {
            maxRetries?: number;
            strategy?: "exponential" | "static" | "linear";
            baseDelayMs?: number;
            maxDelayMs?: number;
          };
          inputs?: {
            [key: string]: string;
          };
          inputSchema?: {
            [key: string]: unknown;
          };
          outputSchema?: {
            [key: string]: unknown;
          };
        }>;
        onNodeFailure?: "fail" | "continue";
      };
      triggers?: Array<
        | {
            type: "webhook";
            hmacSecret?: string;
            hmacHeader?: string;
          }
        | {
            type: "schedule";
            scheduleId: string;
          }
      >;
      cooldown?: {
        hours?: number;
        minutes?: number;
        seconds?: number;
      };
      input?: {
        [key: string]: string | string | string;
      };
      triggerSchema?: {
        [key: string]: unknown;
      };
      dir?: string;
      vcsRepo?: string;
    },
    unknown
  >;
  postApiWorkflowsIdTrigger: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  postApiWorkflowsIdTriggerValidate: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  postStatusTestConnection: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      provider: "claude" | "codex" | "pi" | "devin" | "claude-managed" | "opencode";
    },
    {
      ok: boolean;
      error?: string;
      latency_ms: number;
    }
  >;
  postSwarmApiPath: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  putApiActiveSessionsHeartbeatTaskId: ApiOperation<
    {
      taskId: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  putApiActiveSessionsProviderSessionTaskId: ApiOperation<
    {
      taskId: string;
    },
    EmptyObject,
    {
      providerSessionId: string;
    },
    unknown
  >;
  putApiAgentsIdActivity: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    void
  >;
  putApiAgentsIdCredentialStatus: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      ready?: boolean;
      missing?: Array<string> | null;
      cred_status?:
        | {
            ready: boolean;
            missing?: Array<string>;
            satisfiedBy?: "env" | "file" | "side-effect-pending" | "sdk-delegated" | null;
            hint?: string | null;
            liveTest?:
              | {
                  ok: boolean;
                  error?: string | null;
                  latency_ms: number;
                  testedAt: number;
                }
              | {
                  ok: boolean;
                  error?: string | null;
                  latency_ms: number;
                  testedAt: number;
                };
            latestModel?:
              | {
                  model: string;
                  source: "task" | "agent_config" | "adapter_default" | "custom";
                  taskId?: string | null;
                  harnessProvider?:
                    | "claude"
                    | "codex"
                    | "pi"
                    | "devin"
                    | "claude-managed"
                    | "opencode"
                    | null;
                  reportedAt: number;
                }
              | {
                  model: string;
                  source: "task" | "agent_config" | "adapter_default" | "custom";
                  taskId?: string | null;
                  harnessProvider?:
                    | "claude"
                    | "codex"
                    | "pi"
                    | "devin"
                    | "claude-managed"
                    | "opencode"
                    | null;
                  reportedAt: number;
                };
            reportedAt: number;
            reportKind?: "boot" | "post_task";
            bedrock?:
              | {
                  region: string;
                  probedAt: number;
                  ready: boolean;
                  models?: Array<{
                    id: string;
                    name: string;
                  }>;
                  error?: string;
                }
              | {
                  region: string;
                  probedAt: number;
                  ready: boolean;
                  models?: Array<{
                    id: string;
                    name: string;
                  }>;
                  error?: string;
                };
          }
        | {
            ready: boolean;
            missing?: Array<string>;
            satisfiedBy?: "env" | "file" | "side-effect-pending" | "sdk-delegated" | null;
            hint?: string | null;
            liveTest?:
              | {
                  ok: boolean;
                  error?: string | null;
                  latency_ms: number;
                  testedAt: number;
                }
              | {
                  ok: boolean;
                  error?: string | null;
                  latency_ms: number;
                  testedAt: number;
                };
            latestModel?:
              | {
                  model: string;
                  source: "task" | "agent_config" | "adapter_default" | "custom";
                  taskId?: string | null;
                  harnessProvider?:
                    | "claude"
                    | "codex"
                    | "pi"
                    | "devin"
                    | "claude-managed"
                    | "opencode"
                    | null;
                  reportedAt: number;
                }
              | {
                  model: string;
                  source: "task" | "agent_config" | "adapter_default" | "custom";
                  taskId?: string | null;
                  harnessProvider?:
                    | "claude"
                    | "codex"
                    | "pi"
                    | "devin"
                    | "claude-managed"
                    | "opencode"
                    | null;
                  reportedAt: number;
                };
            reportedAt: number;
            reportKind?: "boot" | "post_task";
            bedrock?:
              | {
                  region: string;
                  probedAt: number;
                  ready: boolean;
                  models?: Array<{
                    id: string;
                    name: string;
                  }>;
                  error?: string;
                }
              | {
                  region: string;
                  probedAt: number;
                  ready: boolean;
                  models?: Array<{
                    id: string;
                    name: string;
                  }>;
                  error?: string;
                };
          };
      latest_model?: {
        model: string;
        source: "task" | "agent_config" | "adapter_default" | "custom";
        taskId?: string | null;
        harnessProvider?:
          | "claude"
          | "codex"
          | "pi"
          | "devin"
          | "claude-managed"
          | "opencode"
          | null;
        reportedAt: number;
      };
    },
    unknown
  >;
  putApiAgentsIdName: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      name: string;
    },
    unknown
  >;
  putApiAgentsIdProfile: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      role?: string;
      description?: string;
      capabilities?: Array<string>;
      claudeMd?: string;
      soulMd?: string;
      identityMd?: string;
      setupScript?: string;
      toolsMd?: string;
      heartbeatMd?: string;
      changeSource?: string;
      changedByAgentId?: string;
      changeReason?: string;
    },
    unknown
  >;
  putApiBudgetsScopeScopeId: ApiOperation<
    {
      scope: "global" | "agent" | "user";
      scopeId: string;
    },
    EmptyObject,
    {
      dailyBudgetUsd: number;
    },
    {
      scope: "global" | "agent" | "user";
      scopeId: string;
      dailyBudgetUsd: number;
      createdAt: number;
      lastUpdatedAt: number;
    }
  >;
  putApiConfig: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      scope: "global" | "agent" | "repo";
      scopeId?: string | null;
      key: string;
      value?: unknown;
      isSecret?: boolean;
      envPath?: string | null;
      description?: string | null;
    },
    unknown
  >;
  putApiKvKey: ApiOperation<
    {
      key: string;
    },
    EmptyObject,
    {
      value?: unknown;
      valueType?: "json" | "string" | "integer";
      expiresInSec?: number;
    },
    unknown
  >;
  putApiKvNamespaceKey: ApiOperation<
    {
      namespace: string;
      key: string;
    },
    EmptyObject,
    {
      value?: unknown;
      valueType?: "json" | "string" | "integer";
      expiresInSec?: number;
    },
    unknown
  >;
  putApiMcpServersId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      [key: string]: unknown;
    },
    unknown
  >;
  putApiPagesId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      title?: string;
      description?: string | null;
      contentType?: "text/html" | "application/json";
      authMode?: "public" | "authed" | "password";
      password?: string | null;
      body?: string;
      needsCredentials?: Array<string> | null;
    },
    unknown
  >;
  putApiPromptTemplates: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      eventType: string;
      scope?: "global" | "agent" | "repo";
      scopeId?: string;
      state?: "enabled" | "default_prompt_fallback" | "skip_event";
      body: string;
      changedBy?: string;
      changeReason?: string;
    },
    unknown
  >;
  putApiReposId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      url?: string;
      name?: string;
      clonePath?: string;
      defaultBranch?: string;
      autoClone?: boolean;
      hooks?:
        | {
            enabled?: boolean;
          }
        | {
            enabled?: boolean;
          };
      guidelines?:
        | {
            prChecks: Array<string>;
            mergeChecks: Array<string>;
            allowMerge?: boolean;
            review: Array<string>;
          }
        | {
            prChecks: Array<string>;
            mergeChecks: Array<string>;
            allowMerge?: boolean;
            review: Array<string>;
          };
    },
    {
      id: string;
      url: string;
      name: string;
      clonePath: string;
      defaultBranch?: string;
      autoClone?: boolean;
      hooks?: {
        enabled?: boolean;
      };
      guidelines?:
        | {
            prChecks: Array<string>;
            mergeChecks: Array<string>;
            allowMerge?: boolean;
            review: Array<string>;
          }
        | {
            prChecks: Array<string>;
            mergeChecks: Array<string>;
            allowMerge?: boolean;
            review: Array<string>;
          };
      createdAt: string;
      lastUpdatedAt: string;
    }
  >;
  putApiSchedulesId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      name?: string;
      description?: string;
      cronExpression?: string | null;
      intervalMs?: number | null;
      taskTemplate?: string;
      taskType?: string;
      tags?: Array<string>;
      priority?: number;
      targetAgentId?: string;
      enabled?: boolean;
      timezone?: string;
      model?: string;
      modelTier?: "smol" | "regular" | "smart" | "ultra" | null;
      nextRunAt?: string | null;
    },
    unknown
  >;
  putApiSkillsId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      [key: string]: unknown;
    },
    unknown
  >;
  putApiSkillsIdFilesPath: ApiOperation<
    {
      id: string;
      path: string;
    },
    EmptyObject,
    {
      content: string;
      mimeType?: string;
      isBinary?: boolean;
      size?: number;
    },
    unknown
  >;
  putApiTasksIdSession: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    | {
        claudeSessionId: string;
        provider: "devin";
        model?: string;
        providerMeta: {
          sessionUrl: string;
          maxAcuLimit?: number;
          acuCostUsd?: number;
        };
      }
    | {
        claudeSessionId: string;
        provider?: "claude" | "codex" | "pi" | "claude-managed" | "opencode";
        model?: string;
        providerMeta?: Record<string, unknown>;
        harnessVariant?: string;
        harnessVariantMeta?: {
          [key: string]: unknown;
        };
      },
    unknown
  >;
  putApiWorkflowsId: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    {
      name?: string;
      description?: string;
      definition?: {
        nodes: Array<{
          id: string;
          type: string;
          label?: string;
          config: {
            [key: string]: unknown;
          };
          next?:
            | string
            | Array<string>
            | {
                [key: string]: string;
              };
          validation?: {
            executor?: string;
            config: {
              [key: string]: unknown;
            };
            mustPass?: boolean;
            retry?: {
              maxRetries?: number;
              strategy?: "exponential" | "static" | "linear";
              baseDelayMs?: number;
              maxDelayMs?: number;
            };
          };
          retry?: {
            maxRetries?: number;
            strategy?: "exponential" | "static" | "linear";
            baseDelayMs?: number;
            maxDelayMs?: number;
          };
          inputs?: {
            [key: string]: string;
          };
          inputSchema?: {
            [key: string]: unknown;
          };
          outputSchema?: {
            [key: string]: unknown;
          };
        }>;
        onNodeFailure?: "fail" | "continue";
      };
      triggers?: Array<
        | {
            type: "webhook";
            hmacSecret?: string;
            hmacHeader?: string;
          }
        | {
            type: "schedule";
            scheduleId: string;
          }
      >;
      cooldown?:
        | {
            hours?: number;
            minutes?: number;
            seconds?: number;
          }
        | {
            hours?: number;
            minutes?: number;
            seconds?: number;
          };
      input?: {
        [key: string]: string | string | string;
      } | null;
      triggerSchema?: {
        [key: string]: unknown;
      } | null;
      dir?: string | null;
      vcsRepo?: string | null;
      enabled?: boolean;
    },
    unknown
  >;
  putSwarmApiPath: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  scriptRunsCancel: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    void
  >;
  scriptRunsCreate: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      source: string;
      args?: unknown;
      background?: boolean;
      idempotencyKey?: string;
      scriptName?: string;
      requestedByUserId?: string;
    },
    unknown
  >;
  scriptRunsGet: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  scriptRunsInternalAgentTask: ApiOperation<
    {
      runId: string;
    },
    EmptyObject,
    {
      stepKey: string;
      template?: string;
      task?: string;
      agentId?: string;
      tags?: Array<string>;
      priority?: number;
      offerMode?: boolean;
      dir?: string;
      vcsRepo?: string;
      model?: string;
      parentTaskId?: string;
      requestedByUserId?: string;
      outputSchema?: {
        [key: string]: unknown;
      };
    },
    unknown
  >;
  scriptRunsInternalHeartbeat: ApiOperation<
    {
      runId: string;
    },
    EmptyObject,
    never,
    void
  >;
  scriptRunsInternalRawLlm: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      prompt: string;
      model?: string;
      schema?: {
        [key: string]: unknown;
      };
      fallbackPort?: string;
    },
    unknown
  >;
  scriptRunsInternalStatus: ApiOperation<
    {
      runId: string;
    },
    EmptyObject,
    | {
        status: "completed";
        output?: unknown;
      }
    | {
        status: "failed";
        error?: string;
      }
    | {
        status: "paused";
      },
    void
  >;
  scriptRunsInternalStepCreate: ApiOperation<
    {
      runId: string;
    },
    EmptyObject,
    {
      stepKey: string;
      stepType: string;
      config?: unknown;
      status: "completed" | "failed";
      result?: unknown;
      error?: string;
      durationMs?: number;
    },
    unknown
  >;
  scriptRunsInternalStepGet: ApiOperation<
    {
      runId: string;
      stepKey: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  scriptRunsList: ApiOperation<
    EmptyObject,
    {
      status?: "running" | "paused" | "completed" | "failed" | "cancelled" | "aborted_limit";
      agentId?: string;
      scriptName?: string;
      limit?: number;
      offset?: number | null;
    },
    never,
    unknown
  >;
  scriptsDelete: ApiOperation<
    {
      name: string;
    },
    {
      scope?: "global" | "agent";
    },
    never,
    unknown
  >;
  scriptsGet: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
  scriptsList: ApiOperation<
    EmptyObject,
    {
      scope?: "global" | "agent";
      includeScratch?: "true" | "false";
    },
    never,
    unknown
  >;
  scriptsReembed: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  scriptsRun: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      name?: string;
      source?: string;
      args?: unknown;
      intent?: string;
      scope?: "global" | "agent";
      fsMode?: "none" | "workspace-rw";
      idempotencyKey?: string;
    },
    unknown
  >;
  scriptsSearch: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      query?: string;
      scope?: "global" | "agent";
      limit?: number;
    },
    unknown
  >;
  scriptsTypeDefs: ApiOperation<EmptyObject, EmptyObject, never, unknown>;
  scriptsTypes: ApiOperation<
    {
      name: string;
    },
    {
      scope?: "global" | "agent";
    },
    never,
    unknown
  >;
  scriptsUpsert: ApiOperation<
    EmptyObject,
    EmptyObject,
    {
      name: string;
      source: string;
      description?: string;
      intent?: string;
      scope?: "global" | "agent";
      fsMode?: "none" | "workspace-rw";
    },
    unknown
  >;
  scriptsVersions: ApiOperation<
    {
      id: string;
    },
    EmptyObject,
    never,
    unknown
  >;
}

export type ApiOperationName = keyof ApiOperations;

export interface OperationMetadata {
  method: HttpMethod;
  path: string;
}

export const operations = {
  deleteApiActiveSessionsByTaskTaskId: {
    method: "DELETE",
    path: "/api/active-sessions/by-task/{taskId}",
  },
  deleteApiActiveSessionsId: { method: "DELETE", path: "/api/active-sessions/{id}" },
  deleteApiBudgetsScopeScopeId: { method: "DELETE", path: "/api/budgets/{scope}/{scopeId}" },
  deleteApiConfigId: { method: "DELETE", path: "/api/config/{id}" },
  deleteApiKvKey: { method: "DELETE", path: "/api/kv/{key}" },
  deleteApiKvNamespaceKey: { method: "DELETE", path: "/api/kv/_/{namespace}/{key}" },
  deleteApiMcpOauthMcpServerId: { method: "DELETE", path: "/api/mcp-oauth/{mcpServerId}" },
  deleteApiMcpServersId: { method: "DELETE", path: "/api/mcp-servers/{id}" },
  deleteApiMcpServersIdInstallAgentId: {
    method: "DELETE",
    path: "/api/mcp-servers/{id}/install/{agentId}",
  },
  deleteApiMemoryId: { method: "DELETE", path: "/api/memory/{id}" },
  deleteApiPagesId: { method: "DELETE", path: "/api/pages/{id}" },
  deleteApiPricingProviderModelTokenClassEffectiveFrom: {
    method: "DELETE",
    path: "/api/pricing/{provider}/{model}/{tokenClass}/{effectiveFrom}",
  },
  deleteApiPromptTemplatesId: { method: "DELETE", path: "/api/prompt-templates/{id}" },
  deleteApiReposId: { method: "DELETE", path: "/api/repos/{id}" },
  deleteApiSchedulesId: { method: "DELETE", path: "/api/schedules/{id}" },
  deleteApiSkillsId: { method: "DELETE", path: "/api/skills/{id}" },
  deleteApiSkillsIdFilesPath: { method: "DELETE", path: "/api/skills/{id}/files/{path}" },
  deleteApiSkillsIdInstallAgentId: { method: "DELETE", path: "/api/skills/{id}/install/{agentId}" },
  deleteApiTrackersJiraDisconnect: { method: "DELETE", path: "/api/trackers/jira/disconnect" },
  deleteApiTrackersJiraWebhookId: { method: "DELETE", path: "/api/trackers/jira/webhook/{id}" },
  deleteApiTrackersLinearDisconnect: { method: "DELETE", path: "/api/trackers/linear/disconnect" },
  deleteApiUsersIdIdentitiesKindExternalId: {
    method: "DELETE",
    path: "/api/users/{id}/identities/{kind}/{externalId}",
  },
  deleteApiUsersIdMcpTokensTokenId: {
    method: "DELETE",
    path: "/api/users/{id}/mcp-tokens/{tokenId}",
  },
  deleteApiWorkflowsId: { method: "DELETE", path: "/api/workflows/{id}" },
  deleteSwarmApiPath: { method: "DELETE", path: "/@swarm/api/{path}" },
  getApiActiveSessions: { method: "GET", path: "/api/active-sessions" },
  getApiAgents: { method: "GET", path: "/api/agents" },
  getApiAgentsCredentialStatus: { method: "GET", path: "/api/agents/credential-status" },
  getApiAgentsId: { method: "GET", path: "/api/agents/{id}" },
  getApiAgentsIdCredentialStatus: { method: "GET", path: "/api/agents/{id}/credential-status" },
  getApiAgentsIdMcpServers: { method: "GET", path: "/api/agents/{id}/mcp-servers" },
  getApiAgentsIdSetupScript: { method: "GET", path: "/api/agents/{id}/setup-script" },
  getApiAgentsIdSkills: { method: "GET", path: "/api/agents/{id}/skills" },
  getApiAgentsIdSkillsSignature: { method: "GET", path: "/api/agents/{id}/skills/signature" },
  getApiApprovalRequests: { method: "GET", path: "/api/approval-requests" },
  getApiApprovalRequestsId: { method: "GET", path: "/api/approval-requests/{id}" },
  getApiBudgets: { method: "GET", path: "/api/budgets" },
  getApiBudgetsRefusals: { method: "GET", path: "/api/budgets/refusals" },
  getApiBudgetsScopeScopeId: { method: "GET", path: "/api/budgets/{scope}/{scopeId}" },
  getApiConcurrentContext: { method: "GET", path: "/api/concurrent-context" },
  getApiConfig: { method: "GET", path: "/api/config" },
  getApiConfigEnvPresence: { method: "GET", path: "/api/config/env-presence" },
  getApiConfigId: { method: "GET", path: "/api/config/{id}" },
  getApiConfigResolved: { method: "GET", path: "/api/config/resolved" },
  getApiEvents: { method: "GET", path: "/api/events" },
  getApiEventsCounts: { method: "GET", path: "/api/events/counts" },
  getApiExecutorTypes: { method: "GET", path: "/api/executor-types" },
  getApiExecutorTypesType: { method: "GET", path: "/api/executor-types/{type}" },
  getApiInboxState: { method: "GET", path: "/api/inbox-state" },
  getApiIntegrationsMcpUserConfig: { method: "GET", path: "/api/integrations/mcp-user/config" },
  getApiKeysAvailable: { method: "GET", path: "/api/keys/available" },
  getApiKeysCosts: { method: "GET", path: "/api/keys/costs" },
  getApiKeysStatus: { method: "GET", path: "/api/keys/status" },
  getApiKv: { method: "GET", path: "/api/kv" },
  getApiKvKey: { method: "GET", path: "/api/kv/{key}" },
  getApiKvNamespace: { method: "GET", path: "/api/kv/_/{namespace}" },
  getApiKvNamespaceKey: { method: "GET", path: "/api/kv/_/{namespace}/{key}" },
  getApiLogs: { method: "GET", path: "/api/logs" },
  getApiMcpOauthCallback: { method: "GET", path: "/api/mcp-oauth/callback" },
  getApiMcpOauthMcpServerIdAuthorize: {
    method: "GET",
    path: "/api/mcp-oauth/{mcpServerId}/authorize",
  },
  getApiMcpOauthMcpServerIdAuthorizeUrl: {
    method: "GET",
    path: "/api/mcp-oauth/{mcpServerId}/authorize-url",
  },
  getApiMcpOauthMcpServerIdMetadata: {
    method: "GET",
    path: "/api/mcp-oauth/{mcpServerId}/metadata",
  },
  getApiMcpOauthMcpServerIdStatus: { method: "GET", path: "/api/mcp-oauth/{mcpServerId}/status" },
  getApiMcpServers: { method: "GET", path: "/api/mcp-servers" },
  getApiMcpServersId: { method: "GET", path: "/api/mcp-servers/{id}" },
  getApiMemoryEdges: { method: "GET", path: "/api/memory/edges" },
  getApiMemoryHealth: { method: "GET", path: "/api/memory/health" },
  getApiMemoryId: { method: "GET", path: "/api/memory/{id}" },
  getApiMemoryRetrievals: { method: "GET", path: "/api/memory/retrievals" },
  getApiMetrics: { method: "GET", path: "/api/metrics" },
  getApiPages: { method: "GET", path: "/api/pages" },
  getApiPagesActions: { method: "GET", path: "/api/pages/actions" },
  getApiPagesId: { method: "GET", path: "/api/pages/{id}" },
  getApiPagesIdVersions: { method: "GET", path: "/api/pages/{id}/versions" },
  getApiPagesIdVersionsVersion: { method: "GET", path: "/api/pages/{id}/versions/{version}" },
  getApiPausedTasks: { method: "GET", path: "/api/paused-tasks" },
  getApiPoll: { method: "GET", path: "/api/poll" },
  getApiPricing: { method: "GET", path: "/api/pricing" },
  getApiPricingProviderModelTokenClass: {
    method: "GET",
    path: "/api/pricing/{provider}/{model}/{tokenClass}",
  },
  getApiPricingProviderModelTokenClassActive: {
    method: "GET",
    path: "/api/pricing/{provider}/{model}/{tokenClass}/active",
  },
  getApiPromptTemplates: { method: "GET", path: "/api/prompt-templates" },
  getApiPromptTemplatesEvents: { method: "GET", path: "/api/prompt-templates/events" },
  getApiPromptTemplatesId: { method: "GET", path: "/api/prompt-templates/{id}" },
  getApiPromptTemplatesResolved: { method: "GET", path: "/api/prompt-templates/resolved" },
  getApiRepos: { method: "GET", path: "/api/repos" },
  getApiReposId: { method: "GET", path: "/api/repos/{id}" },
  getApiScheduledTasks: { method: "GET", path: "/api/scheduled-tasks" },
  getApiSchedules: { method: "GET", path: "/api/schedules" },
  getApiSchedulesId: { method: "GET", path: "/api/schedules/{id}" },
  getApiServices: { method: "GET", path: "/api/services" },
  getApiSessionCosts: { method: "GET", path: "/api/session-costs" },
  getApiSessionCostsDashboard: { method: "GET", path: "/api/session-costs/dashboard" },
  getApiSessionCostsSummary: { method: "GET", path: "/api/session-costs/summary" },
  getApiSessions: { method: "GET", path: "/api/sessions" },
  getApiSessionsRootTaskId: { method: "GET", path: "/api/sessions/{rootTaskId}" },
  getApiSkills: { method: "GET", path: "/api/skills" },
  getApiSkillsId: { method: "GET", path: "/api/skills/{id}" },
  getApiSkillsIdFiles: { method: "GET", path: "/api/skills/{id}/files" },
  getApiSkillsIdFilesPath: { method: "GET", path: "/api/skills/{id}/files/{path}" },
  getApiStats: { method: "GET", path: "/api/stats" },
  getApiTasks: { method: "GET", path: "/api/tasks" },
  getApiTasksId: { method: "GET", path: "/api/tasks/{id}" },
  getApiTasksIdContext: { method: "GET", path: "/api/tasks/{id}/context" },
  getApiTasksTaskIdSessionLogs: { method: "GET", path: "/api/tasks/{taskId}/session-logs" },
  getApiTaskTemplates: { method: "GET", path: "/api/task-templates" },
  getApiTrackersJiraAuthorize: { method: "GET", path: "/api/trackers/jira/authorize" },
  getApiTrackersJiraCallback: { method: "GET", path: "/api/trackers/jira/callback" },
  getApiTrackersJiraStatus: { method: "GET", path: "/api/trackers/jira/status" },
  getApiTrackersLinearAuthorize: { method: "GET", path: "/api/trackers/linear/authorize" },
  getApiTrackersLinearCallback: { method: "GET", path: "/api/trackers/linear/callback" },
  getApiTrackersLinearStatus: { method: "GET", path: "/api/trackers/linear/status" },
  getApiUsers: { method: "GET", path: "/api/users" },
  getApiUsersId: { method: "GET", path: "/api/users/{id}" },
  getApiUsersIdEvents: { method: "GET", path: "/api/users/{id}/events" },
  getApiUsersUnmapped: { method: "GET", path: "/api/users/unmapped" },
  getApiWorkflowRunsId: { method: "GET", path: "/api/workflow-runs/{id}" },
  getApiWorkflows: { method: "GET", path: "/api/workflows" },
  getApiWorkflowsId: { method: "GET", path: "/api/workflows/{id}" },
  getApiWorkflowsIdRuns: { method: "GET", path: "/api/workflows/{id}/runs" },
  getApiWorkflowsIdVersions: { method: "GET", path: "/api/workflows/{id}/versions" },
  getApiWorkflowsIdVersionsVersion: {
    method: "GET",
    path: "/api/workflows/{id}/versions/{version}",
  },
  getEcosystem: { method: "GET", path: "/ecosystem" },
  getPId: { method: "GET", path: "/p/{id}" },
  getPIdJson: { method: "GET", path: "/p/{id}.json" },
  getStatus: { method: "GET", path: "/status" },
  getSwarmApiPath: { method: "GET", path: "/@swarm/api/{path}" },
  patchApiAgentsIdHarnessProvider: { method: "PATCH", path: "/api/agents/{id}/harness-provider" },
  patchApiAgentsIdRuntime: { method: "PATCH", path: "/api/agents/{id}/runtime" },
  patchApiInboxState: { method: "PATCH", path: "/api/inbox-state" },
  patchApiKeysName: { method: "PATCH", path: "/api/keys/name" },
  patchApiTasksIdVcs: { method: "PATCH", path: "/api/tasks/{id}/vcs" },
  patchApiUsersId: { method: "PATCH", path: "/api/users/{id}" },
  patchApiWorkflowsId: { method: "PATCH", path: "/api/workflows/{id}" },
  patchApiWorkflowsIdNodesNodeId: { method: "PATCH", path: "/api/workflows/{id}/nodes/{nodeId}" },
  patchSwarmApiPath: { method: "PATCH", path: "/@swarm/api/{path}" },
  postApiActiveSessions: { method: "POST", path: "/api/active-sessions" },
  postApiActiveSessionsCleanup: { method: "POST", path: "/api/active-sessions/cleanup" },
  postApiActiveSessionsRecoverOrphanedTasks: {
    method: "POST",
    path: "/api/active-sessions/recover-orphaned-tasks",
  },
  postApiAgentmailWebhook: { method: "POST", path: "/api/agentmail/webhook" },
  postApiAgents: { method: "POST", path: "/api/agents" },
  postApiApprovalRequests: { method: "POST", path: "/api/approval-requests" },
  postApiApprovalRequestsIdRespond: { method: "POST", path: "/api/approval-requests/{id}/respond" },
  postApiChannelActivityCommitCursors: {
    method: "POST",
    path: "/api/channel-activity/commit-cursors",
  },
  postApiConfigReload: { method: "POST", path: "/api/config/reload" },
  postApiDbQuery: { method: "POST", path: "/api/db-query" },
  postApiEvents: { method: "POST", path: "/api/events" },
  postApiEventsBatch: { method: "POST", path: "/api/events/batch" },
  postApiGithubWebhook: { method: "POST", path: "/api/github/webhook" },
  postApiGitlabWebhook: { method: "POST", path: "/api/gitlab/webhook" },
  postApiHeartbeatChecklist: { method: "POST", path: "/api/heartbeat/checklist" },
  postApiHeartbeatSweep: { method: "POST", path: "/api/heartbeat/sweep" },
  postApiIntegrationsClaudeManagedTest: {
    method: "POST",
    path: "/api/integrations/claude-managed/test",
  },
  postApiIntegrationsKapsoWebhook: { method: "POST", path: "/api/integrations/kapso/webhook" },
  postApiKeysClearRateLimit: { method: "POST", path: "/api/keys/clear-rate-limit" },
  postApiKeysReportRateLimit: { method: "POST", path: "/api/keys/report-rate-limit" },
  postApiKeysReportRateLimitWindows: {
    method: "POST",
    path: "/api/keys/report-rate-limit-windows",
  },
  postApiKeysReportUsage: { method: "POST", path: "/api/keys/report-usage" },
  postApiKvKeyIncr: { method: "POST", path: "/api/kv/{key}/incr" },
  postApiKvNamespaceKeyIncr: { method: "POST", path: "/api/kv/_/{namespace}/{key}/incr" },
  postApiMcpBridge: { method: "POST", path: "/api/mcp-bridge" },
  postApiMcpOauthMcpServerIdManualClient: {
    method: "POST",
    path: "/api/mcp-oauth/{mcpServerId}/manual-client",
  },
  postApiMcpOauthMcpServerIdRefresh: {
    method: "POST",
    path: "/api/mcp-oauth/{mcpServerId}/refresh",
  },
  postApiMcpServers: { method: "POST", path: "/api/mcp-servers" },
  postApiMcpServersIdInstall: { method: "POST", path: "/api/mcp-servers/{id}/install" },
  postApiMemoryEdit: { method: "POST", path: "/api/memory/edit" },
  postApiMemoryIndex: { method: "POST", path: "/api/memory/index" },
  postApiMemoryList: { method: "POST", path: "/api/memory/list" },
  postApiMemoryRate: { method: "POST", path: "/api/memory/rate" },
  postApiMemoryReEmbed: { method: "POST", path: "/api/memory/re-embed" },
  postApiMemorySearch: { method: "POST", path: "/api/memory/search" },
  postApiPages: { method: "POST", path: "/api/pages" },
  postApiPagesIdLaunch: { method: "POST", path: "/api/pages/{id}/launch" },
  postApiPricingProviderModelTokenClass: {
    method: "POST",
    path: "/api/pricing/{provider}/{model}/{tokenClass}",
  },
  postApiPromptTemplatesIdCheckout: { method: "POST", path: "/api/prompt-templates/{id}/checkout" },
  postApiPromptTemplatesIdReset: { method: "POST", path: "/api/prompt-templates/{id}/reset" },
  postApiPromptTemplatesPreview: { method: "POST", path: "/api/prompt-templates/preview" },
  postApiPromptTemplatesRender: { method: "POST", path: "/api/prompt-templates/render" },
  postApiRepos: { method: "POST", path: "/api/repos" },
  postApiSchedules: { method: "POST", path: "/api/schedules" },
  postApiSchedulesIdRun: { method: "POST", path: "/api/schedules/{id}/run" },
  postApiSessionCosts: { method: "POST", path: "/api/session-costs" },
  postApiSessionLogs: { method: "POST", path: "/api/session-logs" },
  postApiSkills: { method: "POST", path: "/api/skills" },
  postApiSkillsIdFiles: { method: "POST", path: "/api/skills/{id}/files" },
  postApiSkillsIdInstall: { method: "POST", path: "/api/skills/{id}/install" },
  postApiSkillsInstallRemote: { method: "POST", path: "/api/skills/install-remote" },
  postApiSkillsSyncFilesystem: { method: "POST", path: "/api/skills/sync-filesystem" },
  postApiSkillsSyncRemote: { method: "POST", path: "/api/skills/sync-remote" },
  postApiTasks: { method: "POST", path: "/api/tasks" },
  postApiTasksIdCancel: { method: "POST", path: "/api/tasks/{id}/cancel" },
  postApiTasksIdContext: { method: "POST", path: "/api/tasks/{id}/context" },
  postApiTasksIdFinish: { method: "POST", path: "/api/tasks/{id}/finish" },
  postApiTasksIdPause: { method: "POST", path: "/api/tasks/{id}/pause" },
  postApiTasksIdProgress: { method: "POST", path: "/api/tasks/{id}/progress" },
  postApiTasksIdResume: { method: "POST", path: "/api/tasks/{id}/resume" },
  postApiTasksIdSupersede: { method: "POST", path: "/api/tasks/{id}/supersede" },
  postApiTrackersJiraRefresh: { method: "POST", path: "/api/trackers/jira/refresh" },
  postApiTrackersJiraWebhookRegister: {
    method: "POST",
    path: "/api/trackers/jira/webhook-register",
  },
  postApiTrackersJiraWebhookToken: { method: "POST", path: "/api/trackers/jira/webhook/{token}" },
  postApiTrackersLinearRefresh: { method: "POST", path: "/api/trackers/linear/refresh" },
  postApiTrackersLinearWebhook: { method: "POST", path: "/api/trackers/linear/webhook" },
  postApiUsers: { method: "POST", path: "/api/users" },
  postApiUsersIdIdentities: { method: "POST", path: "/api/users/{id}/identities" },
  postApiUsersIdMcpTokens: { method: "POST", path: "/api/users/{id}/mcp-tokens" },
  postApiUsersIdMerge: { method: "POST", path: "/api/users/{id}/merge" },
  postApiUsersUnmappedKindExternalIdResolve: {
    method: "POST",
    path: "/api/users/unmapped/{kind}/{externalId}/resolve",
  },
  postApiWebhooksWorkflowId: { method: "POST", path: "/api/webhooks/{workflowId}" },
  postApiWorkflowEvents: { method: "POST", path: "/api/workflow-events" },
  postApiWorkflowRunsIdCancel: { method: "POST", path: "/api/workflow-runs/{id}/cancel" },
  postApiWorkflowRunsIdRetry: { method: "POST", path: "/api/workflow-runs/{id}/retry" },
  postApiWorkflowRunsRunIdEvents: { method: "POST", path: "/api/workflow-runs/{runId}/events" },
  postApiWorkflows: { method: "POST", path: "/api/workflows" },
  postApiWorkflowsIdTrigger: { method: "POST", path: "/api/workflows/{id}/trigger" },
  postApiWorkflowsIdTriggerValidate: {
    method: "POST",
    path: "/api/workflows/{id}/trigger/validate",
  },
  postStatusTestConnection: { method: "POST", path: "/status/test-connection" },
  postSwarmApiPath: { method: "POST", path: "/@swarm/api/{path}" },
  putApiActiveSessionsHeartbeatTaskId: {
    method: "PUT",
    path: "/api/active-sessions/heartbeat/{taskId}",
  },
  putApiActiveSessionsProviderSessionTaskId: {
    method: "PUT",
    path: "/api/active-sessions/provider-session/{taskId}",
  },
  putApiAgentsIdActivity: { method: "PUT", path: "/api/agents/{id}/activity" },
  putApiAgentsIdCredentialStatus: { method: "PUT", path: "/api/agents/{id}/credential-status" },
  putApiAgentsIdName: { method: "PUT", path: "/api/agents/{id}/name" },
  putApiAgentsIdProfile: { method: "PUT", path: "/api/agents/{id}/profile" },
  putApiBudgetsScopeScopeId: { method: "PUT", path: "/api/budgets/{scope}/{scopeId}" },
  putApiConfig: { method: "PUT", path: "/api/config" },
  putApiKvKey: { method: "PUT", path: "/api/kv/{key}" },
  putApiKvNamespaceKey: { method: "PUT", path: "/api/kv/_/{namespace}/{key}" },
  putApiMcpServersId: { method: "PUT", path: "/api/mcp-servers/{id}" },
  putApiPagesId: { method: "PUT", path: "/api/pages/{id}" },
  putApiPromptTemplates: { method: "PUT", path: "/api/prompt-templates" },
  putApiReposId: { method: "PUT", path: "/api/repos/{id}" },
  putApiSchedulesId: { method: "PUT", path: "/api/schedules/{id}" },
  putApiSkillsId: { method: "PUT", path: "/api/skills/{id}" },
  putApiSkillsIdFilesPath: { method: "PUT", path: "/api/skills/{id}/files/{path}" },
  putApiTasksIdSession: { method: "PUT", path: "/api/tasks/{id}/session" },
  putApiWorkflowsId: { method: "PUT", path: "/api/workflows/{id}" },
  putSwarmApiPath: { method: "PUT", path: "/@swarm/api/{path}" },
  scriptRunsCancel: { method: "DELETE", path: "/api/script-runs/{id}" },
  scriptRunsCreate: { method: "POST", path: "/api/script-runs" },
  scriptRunsGet: { method: "GET", path: "/api/script-runs/{id}" },
  scriptRunsInternalAgentTask: {
    method: "POST",
    path: "/api/internal/script-runs/{runId}/agent-task",
  },
  scriptRunsInternalHeartbeat: {
    method: "POST",
    path: "/api/internal/script-runs/{runId}/heartbeat",
  },
  scriptRunsInternalRawLlm: { method: "POST", path: "/api/internal/raw-llm" },
  scriptRunsInternalStatus: { method: "POST", path: "/api/internal/script-runs/{runId}/status" },
  scriptRunsInternalStepCreate: { method: "POST", path: "/api/internal/script-runs/{runId}/steps" },
  scriptRunsInternalStepGet: {
    method: "GET",
    path: "/api/internal/script-runs/{runId}/steps/{stepKey}",
  },
  scriptRunsList: { method: "GET", path: "/api/script-runs" },
  scriptsDelete: { method: "DELETE", path: "/api/scripts/{name}" },
  scriptsGet: { method: "GET", path: "/api/scripts/{id}" },
  scriptsList: { method: "GET", path: "/api/scripts" },
  scriptsReembed: { method: "POST", path: "/api/scripts/reembed" },
  scriptsRun: { method: "POST", path: "/api/scripts/run" },
  scriptsSearch: { method: "POST", path: "/api/scripts/search" },
  scriptsTypeDefs: { method: "GET", path: "/api/scripts/type-defs" },
  scriptsTypes: { method: "GET", path: "/api/scripts/{name}/types" },
  scriptsUpsert: { method: "POST", path: "/api/scripts/upsert" },
  scriptsVersions: { method: "GET", path: "/api/scripts/{id}/versions" },
} as const satisfies Record<ApiOperationName, OperationMetadata>;

type RequiredKeys<T extends object> = {
  [K in keyof T]-?: Record<string, never> extends Pick<T, K> ? never : K;
}[keyof T];

type ParamsArg<T extends object> = keyof T extends never ? EmptyObject : { params: T };
type QueryArg<T extends object> = keyof T extends never
  ? EmptyObject
  : RequiredKeys<T> extends never
    ? { query?: T }
    : { query: T };
type BodyArg<T> = [T] extends [never] ? EmptyObject : { body: T };

export type OperationRequest<K extends ApiOperationName> = ParamsArg<ApiOperations[K]["params"]> &
  QueryArg<ApiOperations[K]["query"]> &
  BodyArg<ApiOperations[K]["body"]>;

export type OperationResponse<K extends ApiOperationName> = ApiOperations[K]["response"];

type RequestArgs<K extends ApiOperationName> =
  RequiredKeys<OperationRequest<K>> extends never
    ? [request?: OperationRequest<K>, init?: RequestInit]
    : [request: OperationRequest<K>, init?: RequestInit];

export interface ApiClientOptions {
  baseUrl?: string | URL;
  apiKey?: string;
  agentId?: string;
  fetch?: typeof fetch;
  headers?: HeaderInit | (() => HeaderInit | Promise<HeaderInit>);
}

export class ApiClientError extends Error {
  readonly status: number;
  readonly statusText: string;
  readonly body: unknown;
  readonly response: Response;

  constructor(response: Response, body: unknown) {
    super(`Agent Swarm API request failed: ${response.status} ${response.statusText}`);
    this.name = "ApiClientError";
    this.status = response.status;
    this.statusText = response.statusText;
    this.body = body;
    this.response = response;
  }
}

export function createApiClient(options: ApiClientOptions = {}) {
  return {
    request<K extends ApiOperationName>(
      operation: K,
      ...args: RequestArgs<K>
    ): Promise<OperationResponse<K>> {
      return requestOperation(options, operation, ...args);
    },
  };
}

export async function requestOperation<K extends ApiOperationName>(
  options: ApiClientOptions,
  operation: K,
  ...args: RequestArgs<K>
): Promise<OperationResponse<K>> {
  const metadata = operations[operation];
  const request = (args[0] ?? {}) as {
    params?: Record<string, unknown>;
    query?: Record<string, unknown>;
    body?: unknown;
  };
  const init = (args[1] ?? {}) as RequestInit;
  const fetchImpl = options.fetch ?? fetch;
  const headers = new Headers(init.headers);
  await applyHeaders(headers, options.headers);

  if (options.apiKey && !headers.has("Authorization")) {
    headers.set("Authorization", `Bearer ${options.apiKey}`);
  }
  if (options.agentId && !headers.has("X-Agent-ID")) {
    headers.set("X-Agent-ID", options.agentId);
  }

  const hasJsonBody = Object.hasOwn(request, "body");
  if (hasJsonBody && !headers.has("Content-Type")) {
    headers.set("Content-Type", "application/json");
  }

  const response = await fetchImpl(buildUrl(options.baseUrl, metadata.path, request), {
    ...init,
    method: metadata.method,
    headers,
    body: hasJsonBody ? JSON.stringify(request.body ?? null) : init.body,
  });
  const body = await readResponseBody(response);

  if (!response.ok) {
    throw new ApiClientError(response, body);
  }

  return body as OperationResponse<K>;
}

async function applyHeaders(headers: Headers, source: ApiClientOptions["headers"]): Promise<void> {
  if (!source) return;
  const resolved = typeof source === "function" ? await source() : source;
  for (const [key, value] of new Headers(resolved)) {
    headers.set(key, value);
  }
}

function buildUrl(
  baseUrl: string | URL | undefined,
  pathTemplate: string,
  request: { params?: Record<string, unknown>; query?: Record<string, unknown> },
): URL {
  const base = new URL(String(baseUrl ?? "http://localhost:3013").replace(/\/?$/, "/"));
  const path = pathTemplate.replace(/\{([^}]+)\}/g, (_, name: string) => {
    const value = request.params?.[name];
    if (value === undefined || value === null) {
      throw new Error(`Missing path parameter: ${name}`);
    }
    return encodeURIComponent(String(value));
  });
  const url = new URL(path.replace(/^\//, ""), base);

  for (const [key, value] of Object.entries(request.query ?? {})) {
    appendQueryValue(url, key, value);
  }

  return url;
}

function appendQueryValue(url: URL, key: string, value: unknown): void {
  if (value === undefined || value === null) return;
  if (Array.isArray(value)) {
    for (const item of value) appendQueryValue(url, key, item);
    return;
  }
  if (typeof value === "object") {
    url.searchParams.append(key, JSON.stringify(value));
    return;
  }
  url.searchParams.append(key, String(value));
}

async function readResponseBody(response: Response): Promise<unknown> {
  if (response.status === 204) return undefined;
  const text = await response.text();
  if (!text) return undefined;
  const contentType = response.headers.get("content-type") ?? "";
  if (contentType.includes("application/json")) {
    return JSON.parse(text);
  }
  return text;
}
