import { AbsoluteFill, Audio, Sequence, staticFile } from "remotion";
import { theme } from "../theme";
import { SceneIntro } from "../scenes/swarm-demo/SceneIntro";
import { SceneDemo } from "../scenes/swarm-demo/SceneDemo";
import { SceneOutro } from "../scenes/swarm-demo/SceneOutro";
import type { CursorTrack } from "../cursor-track";

// Cursor track from the v1.81.0 People-tab recording.
// Generated by record-e2e.ts against the local demo stack.
// To update: re-run record-e2e.ts and cp raw/e2e-demo-cursor.json src/cursor-track.json
import sampleCursorTrack from "../cursor-track.json";

// 30s @ 30fps = 900 frames.
// Structure:
//   0-90    (0-3s)    Intro — logo.png + "Agent Swarm" wordmark in Space Grotesk
//   90-765  (3-25.5s) E2E demo footage + real cursor from cursor-track.json
//   765-900 (25.5-30s) Outro — wordmark + agent-swarm.dev
//
// Music: Track 9 "Montauk Point" — placeholder bed, volume 0.10.
// Taras to pick final track from Researcher's 10 candidates.
//
// VO: slot wired below but commented out — Lead generates the VO mp3 and drops it in
// as public/audio/vo.mp3. Uncomment the <Audio vo> line for the final mux.
export const SwarmDemo: React.FC = () => {
  const cursorTrack = sampleCursorTrack as CursorTrack;

  return (
    <AbsoluteFill style={{ backgroundColor: theme.bg, fontFamily: theme.sans }}>
      {/* Music bed — placeholder: Track 9 "Montauk Point" */}
      <Audio src={staticFile("audio/montauk-point.mp3")} volume={0.10} />

      {/* VO drop-in slot — Lead muxes: copy generated VO mp3 → public/audio/vo.mp3 and uncomment */}
      {/* <Audio src={staticFile("audio/vo.mp3")} volume={1.0} /> */}

      <Sequence from={0} durationInFrames={90}>
        <SceneIntro />
      </Sequence>

      <Sequence from={90} durationInFrames={675}>
        <SceneDemo cursorTrack={cursorTrack} />
      </Sequence>

      <Sequence from={765} durationInFrames={135}>
        <SceneOutro />
      </Sequence>
    </AbsoluteFill>
  );
};
